# Generated by Django 2.1.15 on 2022-03-18 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preloans', '0002_auto_20220318_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_address',
            name='loan_items',
        ),
    ]
